### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by TANSHUAI1993** [MicrosoftDocs/SCCMDocs.zh-cn#2]
远程桌面连接 (RDC)：每个托管站点服务器或分发点的计算机都需要 RDC。 RDC 用于生成包签名和执行签名比较。
是否应该是:远程差分压缩 (RDC)：每个托管站点服务器或分发点的计算机都需要 RDC。 RDC 用于生成包签名和执行签名比较。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ca64b14f-ff81-b75b-d321-c8ed3bd70d1c
* Version Independent ID: e5e64b1d-c182-b8e4-d0ea-c78c53fed147
* Content: [准备 Windows Server - Configuration Manager](https://docs.microsoft.com/zh-cn/sccm/core/plan-design/network/prepare-windows-servers#feedback)
* Content Source: [sccm/core/plan-design/network/prepare-windows-servers.md](https://github.com/Microsoft/SCCMDocs.zh-cn/blob/live/sccm/core/plan-design/network/prepare-windows-servers.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by srvbpigh** [comment]
Hello, @TANSHUAI1993
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@TANSHUAI1993

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/sccm/core/plan-design/network/prepare-windows-servers#feedback  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
