### ISSUE TITLE
Forefront Endpoint Protection 2010已经停止支持

### ISSUE THREAD

**Issue by TANSHUAI1993** [MicrosoftDocs/SCCMDocs.zh-cn#5]
Forefront Endpoint Protection 2010已经停止支持,且在WSUS编录中也已经没有了,文档中是否应该用System Center Endpoint Protection 替换Forefront Endpoint Protection 2010.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2a20a2b3-4bee-2b91-5f23-b6e6fcb23f6e
* Version Independent ID: e38ad0a6-cff2-f098-ec97-6fda24d681d1
* Content: [Endpoint Protection 恶意软件定义 - Configuration Manager](https://docs.microsoft.com/zh-cn/sccm/protect/deploy-use/endpoint-definitions-configmgr#feedback)
* Content Source: [sccm/protect/deploy-use/endpoint-definitions-configmgr.md](https://github.com/Microsoft/SCCMDocs.zh-cn/blob/live/sccm/protect/deploy-use/endpoint-definitions-configmgr.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by srvbpigh** [comment]
Hello, @TANSHUAI1993
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@TANSHUAI1993

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 -  https://github.com/MicrosoftDocs/SCCMdocs/issues/1896

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
