### ISSUE TITLE
用于客户端请求安装的端口

### ISSUE THREAD

**Issue by TANSHUAI1993** [MicrosoftDocs/SCCMDocs.zh-cn#6]
在通过安全超文本传输协议 (HTTPS) 进行连接时，用于从客户端计算机连接到管理点的 HTTPS。
--
433（请参阅备注 1， 可用的备用端口）

这是433是否应该修改为443?
文中似乎有四处需要修改

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: db8471b5-b50c-b319-c91f-63e1079bed7a
* Version Independent ID: fcaf4dea-8abe-9816-5e6f-77c6cc8a166d
* Content: [Windows 客户端的防火墙和端口设置 - Configuration Manager](https://docs.microsoft.com/zh-cn/sccm/core/clients/deploy/windows-firewall-and-port-settings-for-clients)
* Content Source: [sccm/core/clients/deploy/windows-firewall-and-port-settings-for-clients.md](https://github.com/Microsoft/SCCMDocs.zh-cn/blob/live/sccm/core/clients/deploy/windows-firewall-and-port-settings-for-clients.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by srvbpigh** [comment]
Hello, @TANSHUAI1993
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by aczechowski** [comment]
Looks like this was fixed with #7 
#please-close
(and could you please check the other localized repos to make sure this isn't elsewhere? I spot checked en-us and es-es, both correctly show 443 [not 433].)

**Comment by CeciAc** [comment]
你好，@TANSHUAI1993
感谢你的反馈。 

我们的工程团队已评审并接受你的建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/sccm/core/clients/deploy/windows-firewall-and-port-settings-for-clients

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 

深深的祝福， 
Microsoft DOCS International Team
