### ISSUE TITLE
the execution of connect-autopilotintune is not valid

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/SCCMDocs.zh-cn#8]
My current system version is 1909, according to the documentation installation and import module (install-moudel azure and install-module windowsautopilotintune and import-module windowsautopilotintune), the execution of connect-autopilotintune is not valid, is the need to restart the boot of the computer? Not in detail in the documentation?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bed718c9-fa4d-d78e-3be2-fbc390a80406
* Version Independent ID: cd67f1d8-70a9-1a70-4d8f-1a8063aa0857
* Content: [面向现有设备的 Windows Autopilot - Configuration Manager](https://docs.microsoft.com/zh-cn/configmgr/osd/deploy-use/windows-autopilot-for-existing-devices)
* Content Source: [sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md](https://github.com/Microsoft/SCCMDocs.zh-cn/blob/live/sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by goxia** [comment]
After testing and validation, I found that connect-msgraph should be used instead of connect-autopilotintune, and if the document ation is correct, then a bug may have occurred on windowsauto modulepilot ver 3.7.

**Comment by srvbpigh** [comment]
Hello, @goxia
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by aczechowski** [comment]
Thanks @goxia for the feedback. I'll need to check with the engineering team.

@CeciAc please move this over to SCCMDocs

Here's the metadata for the target article:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bed718c9-fa4d-d78e-3be2-fbc390a80406
* Version Independent ID: cd67f1d8-70a9-1a70-4d8f-1a8063aa0857
* Content: [Windows Autopilot for existing devices - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/osd/deploy-use/windows-autopilot-for-existing-devices)
* Content Source: [sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by goxia** [comment]
> Thanks @goxia for the feedback. I'll need to check with the engineering team.
> 
> @CeciAc please move this over to SCCMDocs
> 
> Here's the metadata for the target article:
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: bed718c9-fa4d-d78e-3be2-fbc390a80406
> * Version Independent ID: cd67f1d8-70a9-1a70-4d8f-1a8063aa0857
> * Content: [Windows Autopilot for existing devices - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/osd/deploy-use/windows-autopilot-for-existing-devices)
> * Content Source: [sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md)
> * Product: **configuration-manager**
> * Technology: **configmgr-osd**
> * GitHub Login: @aczechowski
> * Microsoft Alias: **aaroncz**

I saw this article "https://oofhours.com/2019/11/02/whats-new-with-the-windowsautopilotintune-powershell-module/"

**Comment by CeciAc** [comment]
Moved to https://github.com/MicrosoftDocs/SCCMdocs/issues/2031
