### ISSUE TITLE
共同管理

### ISSUE THREAD

**Issue by gledev** [MicrosoftDocs/SCCMDocs.zh-cn#9]
安全访问

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: dab78401-88d0-6400-2a71-f39d47a5f812
* Version Independent ID: 85964fba-c503-b728-3935-8b5f0ff0d4e8
* Content: [启用共同管理的条件访问 - Configuration Manager](https://docs.microsoft.com/zh-cn/configmgr/comanage/quickstart-conditional-access#feedback)
* Content Source: [sccm/comanage/quickstart-conditional-access.md](https://github.com/Microsoft/SCCMDocs.zh-cn/blob/live/sccm/comanage/quickstart-conditional-access.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by srvbpigh** [comment]
Hello, @gledev
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
你好， @gledev， 

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？ 

顺祝商祺！ 

Microsoft DOCS 国际团队

**Comment by ticianaciminari** [comment]
你好，@gledev，

我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？ 

顺祝商祺！ 

Microsoft DOCS 国际团队

**Comment by ticianaciminari** [comment]
你好，@gledev，

再次感谢你的评论。 

很遗憾，我们仍然缺少信息，无法处理你的反馈。我们当前将关闭此 GitHub 问题，但我们欢迎你在以后提交更多反馈。 

顺祝商祺！ 

Microsoft DOCS 国际团队
